// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	ID string `json:"id"`
}

func (Product) IsEntity() {}

type Query struct {
}

type Review struct {
	ID      int      `json:"id"`
	Body    string   `json:"body"`
	Product *Product `json:"product"`
}

func (Review) IsEntity() {}

type Subscription struct {
}
